paginate:
  per_page: 10
image_user:
  size: 50
  full_size: 80
  small_size: 30
user:
  per_page: 10
relation:
  followers: "followers"
  following: "following"
courses:
  per_page: 10
subjects:
  per_page: 5
activity:
  course: "Course"
  course_subject: "CourseSubject"
  per_page: 5
  all_activities: "all_activities"
  my_activities: "my_activities"
