paginate:
  per_page: 10
image_user:
  half_size: 50
  full_size: 80
  small_size: 30
user:
  per_page: 10
relation:
  followers: "followers"
  following: "following"
courses:
  per_page: 10
subjects:
  per_page: 5
activity:
  course: "Course"
  subject: "Subject"
  task: "Task"
  user: "User"
  course_subject: "CourseSubject"
  per_page: 10
  all_activities: "all_activities"
  my_activities: "my_activities"
  pagination:
    window: 2
trainee_subjects:
  zero: 0
  all: 100
user_courses:
  zero: 0
  all: 100
mail_from: "admin@example.com"
layout: "mailer"
